config/routes.rb
Medicines::Application.routes.draw do
  resources :medicines
  match '/admin' => 'medicines#index'
  resources :users

  root :to => 'users#index', :page => 'home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
def initialize(user)
    user ||= User.new # guest user
    user.roles.each { |role|
      user.regions.each do |user_region|
      
       role_permissions = role.permissions.where("region_id=?",user_region.id)
       role_permissions.each { |permission|
        can permission.conduct.to_sym, permission.regulator.constantize
      }
      
    end
      cannot :delete, User, :id=>user.id
    }

    if user.role? :admin
      can :manage, :all
    else
      can :read , Medicine
    end
    
  end
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
 attr_accessible :name, :code_for_placing_order,:ordered_qty
 validates :name, :presence=>true
 validates :code_for_placing_order, :presence=>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "admin"
  def index
     @medicines = Medicine.all
     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @medicines }
     end
  end
  def show
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine }
    end
  end
  def new
    @medicine = Medicine.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine }
    end
  end
  def edit
    @medicine = Medicine.find(params[:id])
  end
  def create
    @medicine = Medicine.new(params[:medicine])
    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine has been created successfully.' }
        format.json { render json: @medicine, status: :created, location: @medicine }
      else
        format.html { render action: "new" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @medicine = Medicine.find(params[:id])
    respond_to do |format|
      if @medicine.update_attributes(params[:medicine])
        format.html { redirect_to @medicine, notice: 'Medicine has been successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @medicine = Medicine.find(params[:id])
    @medicine.destroy

    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
     @medicines = Medicine.all
     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @medicines }
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def errors_for(object, message=nil)
    html = ""
    unless object.errors.blank?
      html << "<div class='formErrors #{object.class.name.humanize.downcase}Errors'>\n"
      if message.blank?
        if object.new_record?
          html << "\t\t<h5>There was a problem creating the #{object.class.name.humanize.downcase}</h5>\n"
        else
          html << "\t\t<h5>There was a problem updating the #{object.class.name.humanize.downcase}</h5>\n"
        end    
      else
        html << "<h5>#{message}</h5>"
      end  
      html << "\t\t<ul>\n"
      object.errors.full_messages.each do |error|
        html << "\t\t\t<li>#{error}</li>\n"
      end
      html << "\t\t</ul>\n"
      html << "\t</div>\n"
    end
    html
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicines</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medicines/_form.html.erb
    
<div>
          <div>
            <h3>Name<span>*</span></h3>
            <div>
             <%= f.text_field :name%>
            <h3>Code for order placing<span class="red">*</span></h3>
            <div class="select-field">
             <%= f.text_field :code_for_placing_order%>
            </div>
            </div>
            </div>            
            
            
          </div>
        
        </div>

app/views/medicines/edit.html.erb
<div>
    <h2>Editing Medicine</h2>
    <div >
        <%= form_for(@medicine) do |f| %>
     <%= simple_format (errors_for(@medicine,"Could not update Medicine").html_safe) %>
     <%= render :partial => 'form', :locals => { :f => f } %>

      <div>
        
      
        <div >
        <%= f.submit "Update",:style=>"width:70px" %>
        <input type="button" value="Back" onclick="window.location.href='<%=  medicines_path %>'"  style="width:60px" />
     </div> 
      
      </div>
  
<% end %>
    </div>
    
    </div>

app/views/medicines/index.html.erb
        
        
        <div>
     <span>  <input type="button" value="New Medicine" style="width: 100px;" onclick="window.location.href='<%=  new_medicine_path %>'" /></span>
      
    
       <div>
        <div >
          <h2 >Medicines</h2>
          <table>
            <tr>
             
               <td width="221">ID</td>
               <td width="221">Name</td>
              <td width="250">Code_for_placing_order</td>
              <td width="221">Ordered Qty</td>
              <td width="83">Edit</td>
              <td width="93">Delete</td>
            </tr>
            
           
           
                  
                  <%if !@medicines.blank?%>
                  <% @medicines.each do |r| %>
                    <tr>
                      <td width="221"><%= link_to("#{r.id}", medicine_path(r.id))%></td>
                       <td width="221"><%= "#{r.name}" %></td>
                        <td width="250"><%= "#{r.code_for_placing_order}" %></td>
                        <td width="221"><%= "#{r.ordered_qty}" %></td>
                        <td width="83"><%= link_to(image_tag("edit-icon.png"), edit_medicine_path(r.id))%></td>
                        <td  width="93"><%= link_to(image_tag("delet-btn.png"), r, :confirm => "Are you sure you want to delete medicine?", :method => :delete)%>
                      </td>
                       <% end %>
                   </tr>
                 <%end%>
           
          </table>
       
        </div>
         </div>
      
     
    </div>

app/views/medicines/new.html.erb
<div>
    <h2 >New Medicine</h2>
    <div>
        <%= form_for(@medicine) do |f| %>
        <%= simple_format (errors_for(@medicine,"Could not create Medicine").html_safe) %>
        <%= render :partial => 'form', :locals => { :f => f } %>

      <div>
        
       <div>
      <%= f.submit "Save",:style=>"width:70px"%>
      
       <input type="button" value="Back" onclick="window.location.href='<%=  medicines_path %>'"  style="width:60px"/>
 </div>
      
      </div>
  
<% end %>
    </div>
    
    </div>

app/views/medicines/show.html.erb
<div>
  <span> 
    <input type="button" value="Edit" onclick="window.location.href='<%=  edit_medicine_path(@medicine.id) %>'" />
     <input type="button" value="Back" onclick="window.location.href='<%=  medicines_path %>'" />
  </span>
    <h2>Medicine Details</h2>
     <div  >
   <div>
   <div>
        <span>Name</span>
        <span ><%=  @medicine.name  %></span>
        </div> 
    
     <div >
     <div>
        <span>Code for Ordered placing</span>
        <span><%=  @medicine.code_for_placing_order %></span>
        </div> 
       </div>
      <div>
        <span>Ordered Qty</span>
        <span><%=  @medicine.ordered_qty%></span>
        </div> 
    </div>

 
     
       
        <div style="width: 100% ; float: left">
      
    </div>
     
      </div>
  
    
    
</div>




        
        
        

        
        
        

        
        
        

app/views/users/index.html.erb
        
        
        <div>
    
       <div>
        <div>
          <h2 >Medicines</h2>
          <table>
            <tr>
             
               <td width="221">ID</td>
               <td width="221">Name</td>
              <td width="250">Code_for_placing_order</td>
              <td width="221">Ordered Qty</td>
              <td width="83">Order</td>
            </tr>
            
           
           
                  
                  <%if !@medicines.blank?%>
                  <% @medicines.each do |r| %>
                    <tr>
                      <td width="221"><%=r.id%></td>
                       <td width="221"><%= "#{r.name}" %></td>
                        <td width="250"><%= "#{r.code_for_placing_order}" %></td>
                        <td width="221"><%= "#{r.ordered_qty}" %></td>
                        <td  width="93"><%= link_to(image_tag("order-btn.png"), "#")%>
                      </td>
                       <% end %>
                   </tr>
                 <%end%>
           
          </table>
       
        </div>
         </div>
      
     
    </div>